config/routes.rb
Rails.application.routes.draw do
  # HOME
  root    "home_pages#index"
  get     "home",     to: "home_pages#index"
  get     "dashboard/index"

  # AUTH
  get     "sessions/new"
  get     "/signup",  to: "users#new"
  get     "/login",   to: "sessions#new"
  post    "/login",   to: "sessions#create"
  delete  "/logout",  to: "sessions#destroy"

  # PENGGUNA
  resources :users
  get       "/current/user", to: "users#get_current_user"

  # ORDER
  get   "/order/onepick",                             to: "order#show_list_onepick_order",    as: :show_list_onepick_order
  get   "/order/onepick/new",                         to: "order#show_create_onepick_order",  as: :show_create_onepick_order
  post  "/order/onepick/new",                         to: "order#create_onepick_order",       as: :create_onepick_order
  get   "/order/history",                             to: "order#show_transaction_history",   as: :show_transaction_history
  get   "/transactions",                              to: "order#show_all_transactions",      as: :show_all_transactions
  post  "/transactions/:transaction_id/:new_status",  to: "order#change_transaction_status",  as: :change_transaction_status
  post  "/transactions/:transaction_id/confirm",      to: "order#confirm_transaction",        as: :confirm_transaction
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  skip_before_action :verify_authenticity_token

  def show_list_onepick_order
    user = current_user
    orders = Waste.where(user: user).order('created_at DESC') # data order == data waste
    respond_to do |format|
      format.json { render json: send_success('✅ Berhasil menampilkan daftar pesanan', orders) }
      format.html { render 'list_onepick_order', locals: { orders: orders }}
    end
  end

  def show_create_onepick_order
    render 'create_onepick_order'
  end

  def create_onepick_order
    user = current_user
    jenis_sampah = params['jenis_sampah']
    berat_sampah = params['berat']
    gambar_sampah = params['gambar']
    alamat_penjemputan = params['alamat_penjemputan']

    waste = Waste.new(user: user, jenis_sampah: jenis_sampah, berat: berat_sampah, gambar: gambar_sampah, alamat_penjemputan: alamat_penjemputan)

    if waste.valid?
      ActiveRecord::Base.transaction do
        waste.save
        order = Transaction.new(user: user, delivery_courier: nil, waste: waste, nominal_dibayar: 0, status: 'NEW')

        if order.valid?
          order.save
          send_notification_to_courier(user.nama) 
          flash[:message] = '✅ Berhasil menambahkan pesanan OnePick'

          respond_to do |format|
            format.json { render json: send_success('✅ Berhasil menambahkan pesanan OnePick', order) }
            format.html { redirect_to show_list_onepick_order_path, :status => :ok }
          end
        else
          raise ActiveRecord::Rollback
          flash[:message] = '❌ Gagal menambahkan pesanan OnePick. Data transaksi tidak valid'

          respond_to do |format|
            format.json { render json: send_failed('❌ Gagal menambahkan pesanan OnePick. Data transaksi tidak valid', nil), :status => :bad_request }
            format.html { redirect_to show_create_onepick_order_path, status: :bad_request }
          end
        end

      end
    else
      flash[:message] = '❌ Gagal menambahkan pesanan OnePick. Data Sampah tidak valid'
      respond_to do |format|
        format.json { render json: send_failed('❌ Gagal menambahkan pesanan OnePick. Data Sampah tidak valid', nil), :status => :bad_request }
        format.html { redirect_to show_create_onepick_order_path, status: :bad_request }
      end
    end
  end

  # TODO: send notification to all Kurir account
  def send_notification_to_courier(pengguna_name)
    message = "1 pesanan baru dari Pengguna '#{pengguna_name}'"
    return message
  end

  def show_transaction_history
    user = current_user
    transactions = Transaction.where(user: user).order('created_at DESC')
    respond_to do |format|
      format.json { render json: send_success('✅ Berhasil menampilkan histori transaksi', transactions) }
      format.html { render 'transaction_history', locals: { transactions: transactions } }
    end
  end

  def show_all_transactions
    transactions = Transaction.all()
    respond_to do |format|
      format.json { render json: send_success('✅ Berhasil menampilkan semua pesanan', transactions), :status => :ok }
      format.html { render 'list_all_transactions', locals: { transactions: transactions }, :status => :ok }
    end
  end

  def change_transaction_status
    new_status = params[:new_status]
    transaction_id = params[:transaction_id]
    transaction = Transaction.find(transaction_id)

    if transaction.nil?
      respond_to do |format|
        format.json { render json: send_failed('❌ Gagal mengganti status', transactions), :status => :bad_request }
        format.html { redirect_to show_all_transactions_path , :status => :bad_request }
      end
    end

    transaction.update(status: new_status)
    respond_to do |format|
      format.json { render json: send_success('✅ Berhasil memperbarui status pesanan', transaction), :status => :ok }
      format.html { redirect_to show_all_transactions_path, :status => :ok }
    end
  end

  def confirm_transaction
    transaction_id = params[:transaction_id]
    transaction = Transaction.find(transaction_id)

    if transaction.nil?
      respond_to do |format|
        format.json { render json: send_failed('❌ Gagal mengganti status', transactions), :status => :bad_request }
        format.html { redirect_to show_all_transactions_path , :status => :bad_request }
      end
    end

    # TODO: find a way to handle nominal_bayar
    nominal_bayar = 10000
    transaction.update(status: "PAID", nominal_dibayar: nominal_bayar)
    user = User.find(transaction.user.id)
    new_user_saldo = user.saldo + nominal_bayar
    user.update_column(:saldo, new_user_saldo)

    respond_to do |format|
      format.json { render json: send_success('✅ Berhasil mengkonfirmasi transaksi', transaction), :status => :ok }
      format.html { redirect_to show_all_transactions_path, :status => :ok }
    end
  end

  private
    def waste_params
      params.permit(:user, :jenis_sampah, :berat, :gambar, :alamat_penjemputan)
    end
end

app/views/order/create_onepick_order.html.erb
<div class="panel panel-default">
    <div class="panel-body">
        <form action="/order/onepick/new" method="POST" enctype="multipart/form-data">
        <%= csrf_meta_tags %>
          <div class="form-group">
            <label for="jenis_sampah">Jenis Sampah</label>
            <input type="text" class="form-control" name="jenis_sampah" id="jenis_sampah" placeholder="Masukkan jenis sampah" required>
          </div>

          <div class="form-group">
            <label for="berat_sampah">Berat Sampah (kg)</label>
            <input type="number" class="form-control" name="berat" id="berat_sampah" placeholder="Masukkan berat sampah (kg)" required>
          </div>

          <div class="form-group">
            <label for="gambar_sampah">Gambar Sampah</label>
            <input type="file" accept="image/*" class="form-control" name="gambar" id="gambar_sampah" placeholder="Gambar Sampah" required>
          </div>

          <div class="form-group">
            <label for="alamat_penjemputan">Alamat Penjemputan</label>
            <input type="text" class="form-control" name="alamat_penjemputan" id="alamat_penjemputan" placeholder="Masukkan alamat penjemputan" required>
          </div>

          <div class="form-group">
              <button type="submit" class="btn btn-success">Simpan</button>
              <a href="/order/onepick" class="btn btn-danger btn-md">Batal</a>
          </div>
        </form>             
    </div>
</div>

app/views/order/create_order.html.erb
<div class="panel panel-default">
    <div class="panel-body">
        <form action="/order/onepick" method="POST" enctype="multipart/form-data">
        <%= csrf_meta_tags %>
          <div class="form-group">
            <label for="jenis_sampah">Jenis Sampah</label>
            <input type="text" class="form-control" name="jenis_sampah" id="jenis_sampah" placeholder="Masukkan jenis sampah" required>
          </div>

          <div class="form-group">
            <label for="berat_sampah">Berat Sampah (kg)</label>
            <input type="number" class="form-control" name="berat" id="berat_sampah" placeholder="Masukkan berat sampah (kg)" required>
          </div>


          <div class="form-group">
            <label for="gambar_sampah">Gambar Sampah</label>
            <input type="file" accept="image/*" class="form-control" name="gambar" id="gambar_sampah" placeholder="Gambar Sampah" required>
          </div>

          <div class="form-group">
            <label for="alamat_penjemputan">Alamat Penjemputan</label>
            <input type="text" class="form-control" name="alamat_penjemputan" id="alamat_penjemputan" placeholder="Masukkan alamat penjemputan" required>
          </div>

          <div class="form-group">
              <button type="submit" class="btn btn-success">Simpan</button>
              <a href="/" class="btn btn-danger btn-md">Batal</a>
          </div>
        </form>             
    </div>
</div>

app/views/order/list_all_transactions.html.erb
<h1>List All Transactions</h1>

<% if transactions.length > 0 %>
  <ul>
    <% transactions.each_with_index do |transaction, index| %>
      <li><%= index + 1 %></li>
      <%# <li><%= transaction.delivery_courier.user.nama %></li> %>
      <li><%= transaction.waste.jenis_sampah %></li>
      <li><%= transaction.waste.berat %></li>
      <li><%= transaction.waste.gambar %></li>
      <li><%= transaction.waste.alamat_penjemputan %></li>
      <li><%= transaction.nominal_dibayar %></li>
      <li><%= transaction.status %></li>
      <%# TODO: Button still error %>
      <%# <li><%= button_to "Deliver", change_transaction_status_path, method: :post, params: { new_status: "DELIVERED", transaction_id: transaction.id } %></li> %>
      <%# <li><%= button_to "Cancel", change_transaction_status_path, method: :post, params: { new_status: "CANCELLED", transaction_id: transaction.id } %></li> %>
      <%# <li><%= button_to "Confirm", create_transaction_path, method: :post, params: { transaction_id: transaction.id } %></li> %>
    <% end %>
  </ul>
<% else %>
  <p>kosong</p>
<% end %>

app/views/order/list_onepick_order.html.erb
<h1>List of order</h1>

<% if orders.length > 0 %>
  <ul>
    <% orders.each_with_index do |order, index| %>
      <li><%= index + 1 %></li>
      <li><%= order.jenis_sampah %></li>
      <li><%= order.berat %></li>
      <li><%= order.alamat_penjemputan %></li>
    <% end %>
  </ul>
<% else %>
  <p>kosong</p>
<% end %>

app/views/order/transaction_history.erb
<h1>List of transactions</h1>

<% if transactions.length > 0 %>
  <ul>
    <% transactions.each_with_index do |transaction, index| %>
      <li><%= index + 1 %></li>
      <li><%= transaction.delivery_courier.user.nama %></li>
      <li><%= transaction.waste.jenis_sampah %></li>
      <li><%= transaction.waste.berat %></li>
      <li><%= transaction.waste.gambar %></li>
      <li><%= transaction.waste.alamat_penjemputan %></li>
      <li><%= transaction.nominal_dibayar %></li>
      <li><%= transaction.status %></li>
    <% end %>
  </ul>
<% else %>
  <p>kosong</p>
<% end %>

app/views/order/transaction_history.html.erb
<h1>List of transactions</h1>

<% if transactions.length > 0 %>
  <ul>
    <% transactions.each_with_index do |transaction, index| %>
      <li><%= index + 1 %></li>
      <li><%= transaction.delivery_courier.user.nama %></li>
      <li><%= transaction.waste.jenis_sampah %></li>
      <li><%= transaction.waste.berat %></li>
      <li><%= transaction.waste.gambar %></li>
      <li><%= transaction.waste.alamat_penjemputan %></li>
      <li><%= transaction.nominal_dibayar %></li>
      <li><%= transaction.status %></li>
    <% end %>
  </ul>
<% else %>
  <p>kosong</p>
<% end %>