config/routes.rb
Rails.application.routes.draw do
  # HOME
  root    "home_pages#index"
  get     "home",     to: "home_pages#index"
  get     "dashboard/index"

  # AUTH
  get     "sessions/new"
  get     "/signup",  to: "users#new"
  get     "/login",   to: "sessions#new"
  post    "/login",   to: "sessions#create"
  delete  "/logout",  to: "sessions#destroy"

  # PENGGUNA
  resources :users
  get       "/current/user", to: "users#get_current_user"

  # ORDER
  get   "/order/onepick",                             to: "order#show_list_onepick_order",    as: :show_list_onepick_order
  get   "/order/onepick/new",                         to: "order#show_create_onepick_order",  as: :show_create_onepick_order
  post  "/order/onepick/new",                         to: "order#create_onepick_order",       as: :create_onepick_order
  get   "/order/history",                             to: "order#show_transaction_history",   as: :show_transaction_history
  get   "/transactions",                              to: "order#show_all_transactions",      as: :show_all_transactions
  post  "/transactions/:transaction_id/:new_status",  to: "order#change_transaction_status",  as: :change_transaction_status
  post  "/transactions/:transaction_id/confirm",      to: "order#confirm_transaction",        as: :confirm_transaction
end

app/views/layouts/_footer.html.erb
<footer id="dtr-footer" class="dtr-section-with-bg" style="background-image: url(assets/images/footer-bg.png);">
    <div class="container">
        <div class="row"> 
            
            <div class="col-12 col-sm-6 col-lg-4 dtr-mb-30"> <a href="index.html" class="d-block dtr-mb-15"><%= image_tag("oneelite-logo.png", alt: "logo-oneelite") %></a>
                <p>Lorem ipsum dolor sit amet consect adipiscing elit, sed do eiusmod tempor incididunt labore at dolore.</p>
                <p>© 2022 Oneelite Tech. All rights reserved.</p>
            </div>

            <div class="col-12 col-sm-6 col-lg-2 dtr-mb-30">
                <h4 class="color-green">Company</h4>
                <ul class="dtr-list-simple">
                    <li><a href="#" class="dtr-styled-link">Features</a></li>
                    <li><a href="#" class="dtr-styled-link">Plan</a></li>
                    <li><a href="#" class="dtr-styled-link">Blog</a></li>
                    <li><a href="#" class="dtr-styled-link">Contact</a></li>
                </ul>
            </div>
            
            <div class="col-12 col-sm-6 col-lg-2 dtr-mb-30">
                <h4 class="color-green">Support</h4>
                <ul class="dtr-list-simple">
                    <li><a href="#" class="dtr-styled-link">Careers</a></li>
                    <li><a href="#" class="dtr-styled-link">Help</a></li>
                    <li><a href="#" class="dtr-styled-link">Privacy Policy</a></li>
                    <li><a href="#" class="dtr-styled-link">Terms</a></li>
                </ul>
            </div>
            
            <div class="col-12 col-sm-6 col-lg-4 dtr-mb-30">
                <h4 class="color-green">Newsletter</h4>
                <div class="dtr-form dtr-form-has-icon dtr-form-no-gap">
                    <form id="subscribeform" method="post" action="#">
                        <fieldset>
                            <div class="dtr-form-row-2col">
                                <p class="dtr-input dtr-form-column"> <i class="icon-envelope1 color-dark-blue"></i>
                                    <input name="email"  class="required email" type="text" placeholder="Email address">
                                </p>
                                <p class="dtr-form-column">
                                    <button class="dtr-btn btn-green" type="submit">Subscribe</button>
                                </p>
                            </div>
                        </fieldset>
                    </form>
                </div>
                <div class="dtr-social-large">
                    <ul class="dtr-social dtr-social-list color-white-muted-alt accent-color-hover text-center">
                        <li><a href="#" class="dtr-twitter" target="_blank" title="twitter"></a></li>
                        <li><a href="#" class="dtr-facebook" target="_blank" title="facebook"></a></li>
                    </ul>
                </div>
            </div>
            
        </div>
    </div>
</footer>  

app/views/layouts/_header.html.erb
<div class="dtr-responsive-header fixed-top">
    <div class="container"> 
        <%= link_to (image_tag("oneelite-logo.png", alt: "logo-oneelite")) %>
        <button id="dtr-menu-button" class="dtr-hamburger" type="button">
            <span class="dtr-hamburger-lines-wrapper"></span>
            <span class="dtr-hamburger-lines"></span>
        </button>
    </div>
    <div class="dtr-responsive-header-menu"></div>
</div>
    
<header id="dtr-header-global" class="fixed-top bg-white">
    <div class="container">
        <div class="d-flex align-items-center justify-content-between"> 
            
            <div class="dtr-header-left">     
                <%= link_to image_tag("oneelite-logo.png", alt: "logo-oneelite"), root_path, class: "logo-default dtr-scroll-link" %> 
            </div>
            
            <div class="main-navigation navbar navbar-expand-lg ml-auto">
                <ul class="dtr-scrollspy navbar-nav dtr-nav dark-nav-on-load dark-nav-on-scroll navbar-menu">
                    <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link active" %></li>
                    <li class="nav-item"><%= link_to "Fitur", '#feature', class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to "Solusi", '#solusi', class: "nav-link" %></li>
                    <% if logged_in? %>
                        <li class="nav-item">
                            <%= link_to "Users", '#', class: "nav-link" %>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" id="account" class="dropdown-toggle nav-link">
                                Account <b class="caret"></b>
                            </a>
                            <ul id="dropdown-menu" class="dropdown-menu">
                                <li><%= link_to "Profile", current_user %></li>
                                <li><%= link_to "Settings", '#' %></li>
                                <li class="divider"></li>
                                <li>
                                    <%= link_to "Log out", logout_path, data: { "turbo-method": :delete } %>
                                </li>
                            </ul>
                        </li>
                    <% else %>
                        <li>
                            <%= link_to "Log in", login_path %>
                        </li>
                    <% end %>
                </ul>
            </div>
            
            <div class="dtr-header-right">
                <%= link_to "Daftar", signup_path, class: " dtr-btn-flat btn-flat-green  dtr-scroll-link dtr-px-50" %> 
            </div>
            
        </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oneelite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="dtr-wrapper" class="clearfix"> 
        <%= render "layouts/header" %>
            
            <% flash.each do |message_type, message| %>
                <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <%= yield %>
            <%= render "layouts/footer" %>
        
        </div>
    </div>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dashboard Oneelite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="preloader">
        <div id="main-wrapper"> 

            <%= render "shared/header" %>
                <%= yield %>
                <%= render "shared/footer" %>
            </div>

        </div>
    </div>
  </body>
</html>